apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-saas.fullname" . }}-api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: api